#----------------------------------------------------------------------
# This file was generated by E:\taige\cluster-tool-desktop\CEPACClusterLibGui.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

coffee = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAPlJ"
    "REFUWIVjYBgFo2CkA0YC8ueoZM8vBgaGFQwMDBNI1fifBtiB3g64IS4ufpCdnR1ZTJ6eDuiC"
    "GSYuLv4QKvYLJsZEdFhQAbx48UIJymRlYGBgo7sDGBkZ//Ly8sK4GnR3AAMDA8OPHz9gzG90"
    "d0BxcbHO79+/Ydw7xOihRiJs/f//P5O/v787ExMTTGwLzAJCBdF/YlyJDzAyMjL8/49izCcG"
    "BgZ+GIfmUYBm+Uxky4nSTwW8Ap+l9EiEzxkYGD6Sq/kNA+UhIEe+2yHgGwWWt1NqOV1ACwNt"
    "ql1iMAMDAwMD1wBZvgg5FALobPlZ3BEyCkbBKKAzAABEjv0W0bs6kAAAAABJRU5ErkJggg==")

